export const STATUS_LABELS: Record<string, string> = {
  CREATED: "Criado",
  FULFILLMENT_SELECTED: "Selecionando distribuidora",
  STOCK_RESERVED: "Estoque reservado",
  AWAITING_PAYMENT: "Aguardando pagamento",
  PAID: "Pagamento confirmado",
  PARTNER_CONFIRMATION: "Aguardando confirmação da distribuidora",
  ACCEPTED: "Distribuidora aceitou",
  PREPARING: "Em preparo",
  READY_FOR_PICKUP: "Pronto para retirada",
  SEARCHING_DRIVER: "Buscando entregador",
  DRIVER_ASSIGNED: "Entregador a caminho da retirada",
  DRIVER_TO_PICKUP: "Entregador a caminho da retirada",
  PICKED_UP: "Pedido retirado",
  IN_DELIVERY: "A caminho de você",
  DELIVERED: "Entregue",
  CANCELLED: "Cancelado",
  REFUNDED: "Reembolsado",
  PAYMENT_FAILED: "Pagamento falhou",
  DISPUTED: "Em disputa",
  EXPIRED: "Expirado",
};
